version: "3"
services:
  execution-report-monitor:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: execution-report-monitor
    volumes:
      - .:/usr/src/app
    environment:
      - TERM=xterm-256color
    env_file:
      - .env